services:
  postgres-db:
    container_name: db_onlinebookstore
    image: postgres:18.1-alpine
    environment:
      POSTGRES_DB: onlinebookstoredb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: jdbc:postgresdb://localhost:5432/onlinebookstoredb
    ports:
      - "55432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d onlinebookstoredb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - aipoweredonlinebookstore-network

  onlinebookstore:
    container_name: app_onlinebookstore
    build:
      context: ./OnlineBookStore
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/onlinebookstoredb
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8000:8001"
    networks:
      - aipoweredonlinebookstore-network

networks:
  aipoweredonlinebookstore-network:
    driver: bridge
    name: aipoweredonlinebookstore-network

volumes:
  postgres-data:
    driver: local
